version: '2.1'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - monitor-net
    volumes:
      - /etc/hosts:/etc/hosts
      - /home/ubuntu/prometheus-config.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports: 
      - 3000:3000
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

volumes:
    grafana_data: {}
    prometheus_data: {}
    
