---
- name: Download package archive
  unarchive: 
    src: https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz
    dest: /home/ubuntu
    remote_src: yes
    owner: 'ubuntu'
    group: 'ubuntu'

- name: renaming package folder 
  command: mv /home/ubuntu/kafka_{{ scala_version }}-{{ kafka_version }} /home/ubuntu/kafka
  